# Borrowing this setup from codename cause old caching stuff doesn't work anymore
name: Windows Build
on:
  push:
jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
      - name: Installing/Updating libraries
        run: |
          haxelib setup C:/haxelib 
          haxelib git hxcpp https://github.com/Sonamaker1/hxcpp --always > nul 
          haxelib --always set lime 8.0.2 > nul 
          haxelib --never install flixel 5.5.0 > nul 
          haxelib run lime setup flixel > nul 
          haxelib run lime setup > nul 
          haxelib --always set tjson 1.4.0 > nul 
          haxelib --always set openfl 9.2.1 > nul 
          haxelib --always set flixel-tools 1.5.1 > nul 
          haxelib --always set flixel-ui 2.4.0 > nul 
          haxelib --always set flixel-addons 3.2.1 > nul 
          haxelib --always set hxCodec 3.0.2 > nul 
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit > nul 
          haxelib git hscript https://github.com/HaxeFoundation/hscript > nul 
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex > nul 
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc > nul 
          haxelib --always set lime 8.0.2 > nul 
          haxelib git hxcpp https://github.com/Sonamaker1/hxcpp --always > nul 
          haxelib libpath hxcpp
          haxelib install format > nul
          haxelib install hxp > nul
          haxelib list
          haxelib run lime rebuild hxcpp
      - name: Building the game
        run: |
          haxelib run lime build windows
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v2
        with:
          name: ThisEngineBuild
          path: export/release/windows/bin
      - name: Uploading artifact (executable)
        uses: actions/upload-artifact@v2
        with:
          name: Update-Windows
          path: |
            export/release/windows/bin/PsychEngine.exe
            export/release/windows/bin/plugins
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
